name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: ci-node-api

      - name: Run Tests
        run: npm test
        working-directory: ci-node-api

      - name: Run ESLint
        run: npm run lint
        working-directory: ci-node-api

      - name: Build Application
        run: npm run build
        working-directory: ci-node-api
